apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-backoffice
  template:
    metadata:
      labels:
        app: api-backoffice
    spec:
      containers:
        - name: api-backoffice
          image: e-kyc/api-backoffice
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "125m"
          env:
            - name: BACKOFFICE_HTTP_ADDR
              valueFrom:
                configMapKeyRef:
                  key: BACKOFFICE_HTTP_ADDR
                  name: app-config
            - name: BACKOFFICE_DB_DSN
              valueFrom:
                configMapKeyRef:
                  key: BACKOFFICE_DB_DSN
                  name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-backoffice
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: api-backoffice
