apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8080"
  BACKOFFICE_HTTP_ADDR: ":8081"
  BACKOFFICE_DB_DSN: "postgres://postgres:postgres@database-postgres:5432/ekyc_backoffice?sslmode=disable"
  VITE_API_BACKOFFICE_URL: "http://localhost:8081"
  VITE_API_GATEWAY_URL: "http://localhost:8080"
  NEXT_PUBLIC_API_URL: "http://localhost:8080"
  AI_SUPPORT_SERVICE_NAME: "api-AI-support"
  AI_SUPPORT_GRPC_ADDR: "0.0.0.0:50052"
  AI_SUPPORT_HTTP_ADDR: "0.0.0.0:8082"
  AI_SUPPORT_DB_DSN: "postgres://postgres:postgres@database-postgres:5432/ekyc_backoffice?sslmode=disable"
  AI_SUPPORT_RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
  AI_SUPPORT_FACE_QUEUE: "ai.face_match.jobs"
  AI_SUPPORT_FACE_RESULT_QUEUE: "ai.face_match.results"
  AI_SUPPORT_LIVENESS_QUEUE: "ai.liveness.jobs"
  AI_SUPPORT_LIVENESS_RESULT_QUEUE: "ai.liveness.results"
